platform: linux

image_resource:
  type: docker-image
  source:
    repository:
      548760365095.dkr.ecr.eu-west-1.amazonaws.com/dgw-pulse-replacement/deploy

inputs:
- name: code
- name: manifest

run:
  path:
    code/ci/scripts/checkout-and-deploy.sh
